const questions = [
    {question: "What is the capital of France?", answers: ["Berlin", "Paris", "Madrid", "Rome"], correct: 1},
    {question: "Which planet is known as the Red Planet?", answers: ["Earth", "Saturn", "Mars", "Venus"], correct: 2},
    {question: "Which language is used for web apps?", answers: ["Python", "JavaScript", "C++", "Java"], correct: 1},
    {question: "How many continents are there on Earth?", answers: ["5", "6", "7", "8"], correct: 2},
    {question: "Who wrote 'Romeo and Juliet'?", answers: ["William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"], correct: 0},
    {question: "What is the largest ocean on Earth?", answers: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], correct: 3},
    {question: "What is the boiling point of water?", answers: ["90°C", "100°C", "120°C", "80°C"], correct: 1},
    {question: "Who painted the Mona Lisa?", answers: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correct: 1},
    {question: "Which country is known as the Land of the Rising Sun?", answers: ["China", "Japan", "South Korea", "Thailand"], correct: 1},
    {question: "Who discovered gravity?", answers: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Nikola Tesla"], correct: 1},
    {question: "Which element has the chemical symbol O?", answers: ["Gold", "Oxygen", "Silver", "Iron"], correct: 1},
    {question: "What is the smallest prime number?", answers: ["0", "1", "2", "3"], correct: 2},
    {question: "Which continent is Egypt in?", answers: ["Asia", "Africa", "Europe", "Australia"], correct: 1},
    {question: "What is the process by which plants make food?", answers: ["Respiration", "Photosynthesis", "Germination", "Fermentation"], correct: 1},
    {question: "What is the hardest natural substance?", answers: ["Gold", "Iron", "Diamond", "Quartz"], correct: 2},
    {question: "Who is known as the father of computers?", answers: ["Charles Babbage", "Alan Turing", "Bill Gates", "Steve Jobs"], correct: 0},
    {question: "Which gas do humans need to breathe?", answers: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], correct: 0},
    {question: "What is the main language spoken in Brazil?", answers: ["Spanish", "Portuguese", "French", "English"], correct: 1},
    {question: "Which animal is the largest mammal?", answers: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], correct: 1},
    {question: "What is the freezing point of water?", answers: ["-10°C", "0°C", "10°C", "100°C"], correct: 1},
    {question: "Who invented the telephone?", answers: ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Michael Faraday"], correct: 0},
    {question: "Which is the smallest planet in our solar system?", answers: ["Mercury", "Mars", "Venus", "Neptune"], correct: 0},
    {question: "Who wrote 'The Hobbit'?", answers: ["C.S. Lewis", "J.K. Rowling", "J.R.R. Tolkien", "George R.R. Martin"], correct: 2},
    {question: "Which is the longest river in the world?", answers: ["Amazon", "Nile", "Yangtze", "Mississippi"], correct: 1},
    {question: "What is H2O commonly known as?", answers: ["Water", "Oxygen", "Hydrogen", "Salt"], correct: 0},
    {question: "Who is the author of 'Harry Potter'?", answers: ["J.K. Rowling", "Stephen King", "Suzanne Collins", "Roald Dahl"], correct: 0},
    {question: "Which country hosted the 2016 Summer Olympics?", answers: ["China", "Brazil", "UK", "Russia"], correct: 1},
    {question: "What is the largest desert on Earth?", answers: ["Sahara", "Gobi", "Antarctic", "Kalahari"], correct: 2},
    {question: "Which instrument has 88 keys?", answers: ["Guitar", "Violin", "Piano", "Flute"], correct: 2},
    {question: "Who was the first person to walk on the moon?", answers: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "John Glenn"], correct: 2},
    {question: "What is the capital city of Australia?", answers: ["Sydney", "Melbourne", "Canberra", "Perth"], correct: 2},
    {question: "What is the tallest mountain in the world?", answers: ["K2", "Kangchenjunga", "Mount Everest", "Lhotse"], correct: 2},
    {question: "Which country gifted the Statue of Liberty to the USA?", answers: ["France", "UK", "Germany", "Spain"], correct: 0},
    {question: "What is the main ingredient in sushi?", answers: ["Rice", "Bread", "Pasta", "Potato"], correct: 0},
    {question: "Which scientist developed the theory of relativity?", answers: ["Isaac Newton", "Nikola Tesla", "Albert Einstein", "Marie Curie"], correct: 2},
    {question: "What is the largest organ in the human body?", answers: ["Heart", "Skin", "Liver", "Lungs"], correct: 1},
    {question: "Which is the largest continent?", answers: ["Africa", "Asia", "Europe", "North America"], correct: 1},
    {question: "What is the main currency of Japan?", answers: ["Yen", "Won", "Dollar", "Peso"], correct: 0},
    {question: "Who was the first President of the United States?", answers: ["John Adams", "Thomas Jefferson", "Abraham Lincoln", "George Washington"], correct: 3},
    {question: "Which metal is liquid at room temperature?", answers: ["Mercury", "Gold", "Silver", "Copper"], correct: 0},
    {question: "What is the chemical symbol for gold?", answers: ["Gd", "Go", "Au", "Ag"], correct: 2},
    {question: "Who is known as the 'King of Pop'?", answers: ["Elvis Presley", "Michael Jackson", "Prince", "Freddie Mercury"], correct: 1},
    {question: "Which fruit is the most widely consumed in the world?", answers: ["Banana", "Apple", "Grapes", "Mango"], correct: 0},
    {question: "What is the largest bird in the world?", answers: ["Eagle", "Ostrich", "Penguin", "Albatross"], correct: 1},
    {question: "Which is the smallest country in the world?", answers: ["Monaco", "Nauru", "Vatican City", "San Marino"], correct: 2},
    {question: "What is the capital of Canada?", answers: ["Toronto", "Vancouver", "Ottawa", "Montreal"], correct: 2},
    {question: "Which food is high in Vitamin C?", answers: ["Bread", "Orange", "Rice", "Potato"], correct: 1},
    {question: "Which planet is closest to the sun?", answers: ["Venus", "Mercury", "Mars", "Earth"], correct: 1},
    {question: "What is the national flower of Japan?", answers: ["Rose", "Tulip", "Cherry Blossom", "Lily"], correct: 2},
    {question: "Which organ pumps blood through the body?", answers: ["Liver", "Heart", "Lungs", "Kidney"], correct: 1},
    {question: "Who is the Greek god of war?", answers: ["Zeus", "Apollo", "Ares", "Poseidon"], correct: 2},
    {question: "What is the main ingredient in guacamole?", answers: ["Tomato", "Potato", "Avocado", "Pepper"], correct: 2},
    {question: "Which city is famous for the Colosseum?", answers: ["Athens", "Rome", "Paris", "Istanbul"], correct: 1},
    {question: "What is the currency of the UK?", answers: ["Euro", "Dollar", "Pound Sterling", "Franc"], correct: 2},
    {question: "Who invented the lightbulb?", answers: ["Thomas Edison", "James Watt", "Alexander Fleming", "Isaac Newton"], correct: 0},
    {question: "Which animal is on the Australian coat of arms?", answers: ["Lion", "Kangaroo", "Tiger", "Bear"], correct: 1},
    {question: "What is the largest island in the world?", answers: ["Greenland", "Australia", "Borneo", "Sumatra"], correct: 0},
    {question: "Who was the first woman to win a Nobel Prize?", answers: ["Marie Curie", "Mother Teresa", "Rosalind Franklin", "Ada Lovelace"], correct: 0},
    {question: "What is the square root of 81?", answers: ["7", "8", "9", "10"], correct: 2},
    {question: "Which planet has the most moons?", answers: ["Earth", "Jupiter", "Mars", "Saturn"], correct: 1},
    {question: "Which is the longest bone in the human body?", answers: ["Tibia", "Femur", "Humerus", "Fibula"], correct: 1},
    {question: "What is the capital of India?", answers: ["Mumbai", "New Delhi", "Bangalore", "Chennai"], correct: 1},
    {question: "What is the main ingredient in hummus?", answers: ["Lentils", "Chickpeas", "Beans", "Peas"], correct: 1},
    {question: "Which U.S. state is known as the 'Sunshine State'?", answers: ["California", "Texas", "Florida", "Nevada"], correct: 2},
    {question: "Who wrote 'Pride and Prejudice'?", answers: ["Jane Austen", "Emily Bronte", "Virginia Woolf", "Agatha Christie"], correct: 0},
    {question: "What is the largest land animal?", answers: ["Lion", "Giraffe", "Elephant", "Rhino"], correct: 2},
    {question: "What is the formula for area of a circle?", answers: ["πr^2", "2πr", "l x w", "b x h"], correct: 0},
    {question: "Which blood type is known as the universal donor?", answers: ["A", "B", "O negative", "AB"], correct: 2},
    {question: "What is the highest mountain in Africa?", answers: ["Mount Kenya", "Mount Kilimanjaro", "Mount Elgon", "Mount Meru"], correct: 1},
    {question: "Which planet is known for its rings?", answers: ["Mars", "Venus", "Saturn", "Jupiter"], correct: 2},
    {question: "Who is the main character in 'The Catcher in the Rye'?", answers: ["Harry Potter", "Holden Caulfield", "Jay Gatsby", "Tom Sawyer"], correct: 1},
    {question: "What is the hardest rock?", answers: ["Marble", "Granite", "Diamond", "Quartz"], correct: 2},
    {question: "Which continent has the most countries?", answers: ["Asia", "Africa", "Europe", "South America"], correct: 1},
    {question: "What is the largest internal organ in the human body?", answers: ["Heart", "Liver", "Lung", "Kidney"], correct: 1},
    {question: "Which is the only mammal capable of true flight?", answers: ["Bat", "Flying Squirrel", "Sugar Glider", "Eagle"], correct: 0},
    {question: "Who was the scientist who classified elements into a periodic table?", answers: ["Mendeleev", "Einstein", "Newton", "Bohr"], correct: 0},
    {question: "Which is the fastest land animal?", answers: ["Cheetah", "Lion", "Horse", "Gazelle"], correct: 0},
    {question: "What is the capital of Spain?", answers: ["Barcelona", "Madrid", "Seville", "Valencia"], correct: 1},
    {question: "Which is the largest volcano on Earth?", answers: ["Mount Etna", "Mount Fuji", "Mauna Loa", "Krakatoa"], correct: 2},
    {question: "What is the closest star to Earth?", answers: ["Sirius", "Betelgeuse", "Alpha Centauri", "The Sun"], correct: 3},
    {question: "What is the main gas found in the air we breathe?", answers: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], correct: 1},
    {question: "Which is the largest freshwater lake in the world?", answers: ["Lake Superior", "Lake Victoria", "Lake Baikal", "Lake Tanganyika"], correct: 0},
    {question: "Which planet is known as the Morning Star?", answers: ["Venus", "Mars", "Mercury", "Jupiter"], correct: 0},
    {question: "Who is the famous detective created by Arthur Conan Doyle?", answers: ["Hercule Poirot", "Sherlock Holmes", "Miss Marple", "Sam Spade"], correct: 1},
    {question: "What is 12 x 12?", answers: ["124", "144", "132", "122"], correct: 1},
    {question: "Which country is called the Land of a Thousand Lakes?", answers: ["Canada", "Sweden", "Finland", "Norway"], correct: 2},
    {question: "What is the chemical symbol for sodium?", answers: ["Na", "So", "Sd", "S"], correct: 0},
    {question: "Who invented the World Wide Web?", answers: ["Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Mark Zuckerberg"], correct: 1},
    {question: "What is the largest species of shark?", answers: ["Great White", "Hammerhead", "Whale Shark", "Tiger Shark"], correct: 2},
    {question: "Which is the largest moon of Jupiter?", answers: ["Europa", "Ganymede", "Io", "Callisto"], correct: 1},
    {question: "Which year did World War II end?", answers: ["1942", "1945", "1947", "1950"], correct: 1},
    {question: "What is the capital of Turkey?", answers: ["Istanbul", "Ankara", "Izmir", "Bursa"], correct: 1},
    {question: "Who is the author of 'Moby Dick'?", answers: ["Mark Twain", "Herman Melville", "Nathaniel Hawthorne", "Jules Verne"], correct: 1},
    {question: "Which animal is a marsupial?", answers: ["Rabbit", "Kangaroo", "Horse", "Cow"], correct: 1},
    {question: "What color is chlorophyll?", answers: ["Red", "Green", "Yellow", "Blue"], correct: 1},
    {question: "What is the main ingredient in traditional Japanese miso soup?", answers: ["Noodles", "Seaweed", "Miso paste", "Rice"], correct: 2},
    {question: "Which city is known as the Big Apple?", answers: ["Los Angeles", "New York", "Chicago", "San Francisco"], correct: 1},
    {question: "What is the largest galaxy in our universe?", answers: ["Andromeda", "Milky Way", "Sombrero", "Whirlpool"], correct: 1},
    {question: "Which is the largest living reptile?", answers: ["Komodo Dragon", "Crocodile", "Alligator", "Turtle"], correct: 1},
    {question: "What is the chemical symbol for potassium?", answers: ["P", "Po", "K", "Pt"], correct: 2},
    {question: "What is the closest star to Earth?", answers: ["Sirius", "Betelgeuse", "Alpha Centauri", "The Sun"], correct: 3, subject: ["science","astronomy"], level: 0},
{question: "Which planet is known for its rings?", answers: ["Jupiter","Mars","Saturn","Neptune"], correct: 2, subject: ["science","astronomy"], level: 2},
{question: "What gas do plants absorb from the atmosphere?", answers: ["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"], correct: 1, subject: ["science","biology"], level: 1},
{question: "What is the capital of Japan?", answers: ["Beijing","Seoul","Kyoto","Tokyo"], correct: 3, subject: ["geography"], level: 1},
{question: "Who painted the Mona Lisa?", answers: ["Michelangelo","Leonardo da Vinci","Raphael","Donatello"], correct: 1, subject: ["art","history"], level: 1},
{question: "Which country is known as the Land of the Rising Sun?", answers: ["China","South Korea","Japan","Thailand"], correct: 2, subject: ["geography","culture"], level: 2},
{question: "What is the chemical symbol for water?", answers: ["WO","O2","H2O","HO2"], correct: 2, subject: ["science","chemistry"], level: 0},
{question: "Which animal is known as the king of the jungle?", answers: ["Elephant","Lion","Tiger","Cheetah"], correct: 1, subject: ["science","zoology"], level: 1},
{question: "What is the square root of 64?", answers: ["6","7","8","9"], correct: 2, subject: ["math"], level: 1},
{question: "What is the largest planet in our solar system?", answers: ["Saturn","Earth","Jupiter","Mars"], correct: 2, subject: ["science","astronomy"], level: 2},
{question: "Who discovered penicillin?", answers: ["Marie Curie","Alexander Fleming","Louis Pasteur","Isaac Newton"], correct: 1, subject: ["science","medicine"], level: 10},
{question: "Which element has the atomic number 1?", answers: ["Oxygen","Helium","Hydrogen","Carbon"], correct: 2, subject: ["science","chemistry"], level: 1},
{question: "What year did World War II end?", answers: ["1944","1945","1946","1947"], correct: 1, subject: ["history","wars"], level: 3},
{question: "Which author wrote '1984'?", answers: ["Aldous Huxley","Ray Bradbury","George Orwell","Ernest Hemingway"], correct: 2, subject: ["literature"], level: 5},
{question: "What process do plants use to turn sunlight into food?", answers: ["Digestion","Photosynthesis","Respiration","Fermentation"], correct: 1, subject: ["science","biology"], level: 1},
{question: "What is the hardest natural substance on Earth?", answers: ["Diamond","Steel","Quartz","Granite"], correct: 0, subject: ["science","geology"], level: 1},
{question: "Which country gifted the Statue of Liberty to the United States?", answers: ["Germany","France","Italy","Spain"], correct: 1, subject: ["history","politics"], level: 2},
{question: "How many bones are in an adult human body?", answers: ["206","205","201","210"], correct: 0, subject: ["science","anatomy"], level: 4},
{question: "What is the main ingredient in bread?", answers: ["Rice","Corn","Flour","Barley"], correct: 2, subject: ["food","general knowledge"], level: 0},
{question: "Who was the first President of the United States?", answers: ["Abraham Lincoln","George Washington","Thomas Jefferson","John Adams"], correct: 1, subject: ["history","US"], level: 1},
{question: "What is the closest star to Earth?", answers: ["Sirius","Betelgeuse","Alpha Centauri","The Sun"], correct: 3, subject: ["science","astronomy"], level: 0},
{question: "Which planet is known for its rings?", answers: ["Jupiter","Mars","Saturn","Neptune"], correct: 2, subject: ["science","astronomy"], level: 2},
{question: "What gas do plants absorb from the atmosphere?", answers: ["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"], correct: 1, subject: ["science","biology"], level: 1},
{question: "What is the capital of Canada?", answers: ["Toronto","Vancouver","Ottawa","Montreal"], correct: 2, subject: ["geography"], level: 1},
{question: "Who painted the Mona Lisa?", answers: ["Michelangelo","Leonardo da Vinci","Raphael","Donatello"], correct: 1, subject: ["art","history"], level: 1},
{question: "What is the largest mammal on Earth?", answers: ["African Elephant","Blue Whale","Giraffe","Sperm Whale"], correct: 1, subject: ["science","zoology"], level: 2},
{question: "What is the chemical symbol for water?", answers: ["WO","O2","H2O","HO2"], correct: 2, subject: ["science","chemistry"], level: 0},
{question: "Which animal is known as the king of the jungle?", answers: ["Elephant","Lion","Tiger","Cheetah"], correct: 1, subject: ["science","zoology"], level: 1},
{question: "What is the square root of 81?", answers: ["7","8","9","10"], correct: 2, subject: ["math"], level: 1},
{question: "What is the largest planet in our solar system?", answers: ["Saturn","Earth","Jupiter","Mars"], correct: 2, subject: ["science","astronomy"], level: 2},
{question: "Who discovered penicillin?", answers: ["Marie Curie","Alexander Fleming","Louis Pasteur","Isaac Newton"], correct: 1, subject: ["science","medicine"], level: 10},
{question: "Which element has the atomic number 1?", answers: ["Oxygen","Helium","Hydrogen","Carbon"], correct: 2, subject: ["science","chemistry"], level: 1},
{question: "What year did World War II end?", answers: ["1944","1945","1946","1947"], correct: 1, subject: ["history","wars"], level: 3},
{question: "Which author wrote '1984'?", answers: ["Aldous Huxley","Ray Bradbury","George Orwell","Ernest Hemingway"], correct: 2, subject: ["literature"], level: 5},
{question: "What process do plants use to turn sunlight into food?", answers: ["Digestion","Photosynthesis","Respiration","Fermentation"], correct: 1, subject: ["science","biology"], level: 1},
{question: "What is the hardest natural substance on Earth?", answers: ["Diamond","Steel","Quartz","Granite"], correct: 0, subject: ["science","geology"], level: 1},
{question: "Which country gifted the Statue of Liberty to the United States?", answers: ["Germany","France","Italy","Spain"], correct: 1, subject: ["history","politics"], level: 2},
{question: "How many bones are in an adult human body?", answers: ["206","205","201","210"], correct: 0, subject: ["science","anatomy"], level: 4},
{question: "What is the main ingredient in bread?", answers: ["Rice","Corn","Flour","Barley"], correct: 2, subject: ["food","general knowledge"], level: 0},
{question: "Who was the first President of the United States?", answers: ["Abraham Lincoln","George Washington","Thomas Jefferson","John Adams"], correct: 1, subject: ["history","US"], level: 1},
{question: "In which year did the Titanic sink?", answers: ["1905","1912","1898","1923"], correct: 1, subject: ["history","maritime"], level: 3},
{question: "What is the capital of Australia?", answers: ["Sydney","Melbourne","Canberra","Brisbane"], correct: 2, subject: ["geography"], level: 2},
{question: "Who wrote the play 'Hamlet'?", answers: ["Christopher Marlowe","William Shakespeare","Ben Jonson","John Webster"], correct: 1, subject: ["literature","plays"], level: 4},
{question: "What is the boiling point of water at sea level in Celsius?", answers: ["90°C","95°C","100°C","105°C"], correct: 2, subject: ["science","physics"], level: 0},
{question: "Which painter cut off his own ear?", answers: ["Claude Monet","Vincent van Gogh","Pablo Picasso","Salvador Dalí"], correct: 1, subject: ["art","history"], level: 4},
{question: "Which language has the most native speakers?", answers: ["English","Spanish","Mandarin Chinese","Hindi"], correct: 2, subject: ["language","geography"], level: 3},
{question: "What is the powerhouse of the cell?", answers: ["Nucleus","Mitochondria","Ribosome","Golgi apparatus"], correct: 1, subject: ["science","biology"], level: 2},
{question: "Which continent is the Sahara Desert located on?", answers: ["Asia","South America","Africa","Australia"], correct: 2, subject: ["geography","nature"], level: 1},
{question: "Who is known as the Father of Computers?", answers: ["Alan Turing","Charles Babbage","John von Neumann","Konrad Zuse"], correct: 1, subject: ["science","technology"], level: 6},
{question: "What is the currency of Japan?", answers: ["Yuan","Yen","Won","Dollar"], correct: 1, subject: ["geography","economics"], level: 1},
{question: "Which gas is most abundant in Earth's atmosphere?", answers: ["Oxygen","Nitrogen","Carbon Dioxide","Argon"], correct: 1, subject: ["science","chemistry"], level: 2},
{question: "What is the capital of Egypt?", answers: ["Cairo","Alexandria","Giza","Luxor"], correct: 0, subject: ["geography"], level: 2},
{question: "Who painted 'Starry Night'?", answers: ["Edgar Degas","Pablo Picasso","Vincent van Gogh","Claude Monet"], correct: 2, subject: ["art","history"], level: 3},
{question: "Which country invented pizza?", answers: ["France","United States","Italy","Greece"], correct: 2, subject: ["food","culture"], level: 1},
{question: "What is H2SO4 commonly known as?", answers: ["Hydrochloric acid","Sulfuric acid","Nitric acid","Acetic acid"], correct: 1, subject: ["science","chemistry"], level: 5},
{question: "Who wrote 'Pride and Prejudice'?", answers: ["Charlotte Brontë","Jane Austen","Emily Brontë","Mary Shelley"], correct: 1, subject: ["literature"], level: 4},
{question: "What year did man first land on the Moon?", answers: ["1965","1969","1972","1959"], correct: 1, subject: ["science","space"], level: 2},
{question: "What is the fastest land animal?", answers: ["Cheetah","Lion","Pronghorn","Horse"], correct: 0, subject: ["science","zoology"], level: 2},
{question: "Which ocean is the largest?", answers: ["Atlantic","Pacific","Indian","Arctic"], correct: 1, subject: ["geography","nature"], level: 1},
{question: "What is the formula for calculating the area of a circle?", answers: ["πr²","2πr","πd","πr³"], correct: 0, subject: ["math"], level: 3},        
{question: "In which year did the Titanic sink?", answers: ["1905","1912","1898","1923"], correct: 1, subject: ["history","maritime"], level: 3},
{question: "What is the capital of Australia?", answers: ["Sydney","Melbourne","Canberra","Brisbane"], correct: 2, subject: ["geography"], level: 2},
{question: "Who wrote the play 'Hamlet'?", answers: ["Christopher Marlowe","William Shakespeare","Ben Jonson","John Webster"], correct: 1, subject: ["literature","plays"], level: 4},
{question: "What is the boiling point of water at sea level in Celsius?", answers: ["90°C","95°C","100°C","105°C"], correct: 2, subject: ["science","physics"], level: 0},
{question: "Which painter cut off his own ear?", answers: ["Claude Monet","Vincent van Gogh","Pablo Picasso","Salvador Dalí"], correct: 1, subject: ["art","history"], level: 4},
{question: "Which language has the most native speakers?", answers: ["English","Spanish","Mandarin Chinese","Hindi"], correct: 2, subject: ["language","geography"], level: 3},
{question: "What is the powerhouse of the cell?", answers: ["Nucleus","Mitochondria","Ribosome","Golgi apparatus"], correct: 1, subject: ["science","biology"], level: 2},
{question: "Which continent is the Sahara Desert located on?", answers: ["Asia","South America","Africa","Australia"], correct: 2, subject: ["geography","nature"], level: 1},
{question: "Who is known as the Father of Computers?", answers: ["Alan Turing","Charles Babbage","John von Neumann","Konrad Zuse"], correct: 1, subject: ["science","technology"], level: 6},
{question: "What is the currency of Japan?", answers: ["Yuan","Yen","Won","Dollar"], correct: 1, subject: ["geography","economics"], level: 1},
{question: "Which gas is most abundant in Earth's atmosphere?", answers: ["Oxygen","Nitrogen","Carbon Dioxide","Argon"], correct: 1, subject: ["science","chemistry"], level: 2},
{question: "What is the capital of Egypt?", answers: ["Cairo","Alexandria","Giza","Luxor"], correct: 0, subject: ["geography"], level: 2},
{question: "Who painted 'Starry Night'?", answers: ["Edgar Degas","Pablo Picasso","Vincent van Gogh","Claude Monet"], correct: 2, subject: ["art","history"], level: 3},
{question: "Which country invented pizza?", answers: ["France","United States","Italy","Greece"], correct: 2, subject: ["food","culture"], level: 1},
{question: "What is H2SO4 commonly known as?", answers: ["Hydrochloric acid","Sulfuric acid","Nitric acid","Acetic acid"], correct: 1, subject: ["science","chemistry"], level: 5},
{question: "Who wrote 'Pride and Prejudice'?", answers: ["Charlotte Brontë","Jane Austen","Emily Brontë","Mary Shelley"], correct: 1, subject: ["literature"], level: 4},
{question: "What year did man first land on the Moon?", answers: ["1965","1969","1972","1959"], correct: 1, subject: ["science","space"], level: 2},
{question: "What is the fastest land animal?", answers: ["Cheetah","Lion","Pronghorn","Horse"], correct: 0, subject: ["science","zoology"], level: 2},
{question: "Which ocean is the largest?", answers: ["Atlantic","Pacific","Indian","Arctic"], correct: 1, subject: ["geography","nature"], level: 1},
{question: "What is the formula for calculating the area of a circle?", answers: ["πr²","2πr","πd","πr³"], correct: 0, subject: ["math"], level: 3},
{question: "Who discovered gravity when an apple fell on his head?", answers: ["Albert Einstein","Galileo Galilei","Isaac Newton","Nikola Tesla"], correct: 2, subject: ["science","physics"], level: 1},
{question: "What is the capital of France?", answers: ["Berlin","Madrid","Paris","Rome"], correct: 2, subject: ["geography"], level: 1},
{question: "Which metal is liquid at room temperature?", answers: ["Mercury","Lead","Silver","Gold"], correct: 0, subject: ["science","chemistry"], level: 2},
{question: "Who is the author of 'Harry Potter'?", answers: ["J.K. Rowling","Stephen King","J.R.R. Tolkien","Suzanne Collins"], correct: 0, subject: ["literature","fantasy"], level: 1},
{question: "What is the smallest prime number?", answers: ["0","1","2","3"], correct: 2, subject: ["math"], level: 0},
{question: "Which city hosted the 2008 Summer Olympics?", answers: ["Athens","Beijing","Sydney","London"], correct: 1, subject: ["sports","history"], level: 3},
{question: "What is the chemical symbol for Iron?", answers: ["Ir","Fe","In","I"], correct: 1, subject: ["science","chemistry"], level: 2},
{question: "In what year did the Berlin Wall fall?", answers: ["1987","1989","1991","1993"], correct: 1, subject: ["history","Europe"], level: 5},
{question: "Who painted the ceiling of the Sistine Chapel?", answers: ["Raphael","Leonardo da Vinci","Michelangelo","Donatello"], correct: 2, subject: ["art","history"], level: 4},
{question: "What language is primarily spoken in Brazil?", answers: ["Spanish","Portuguese","French","English"], correct: 1, subject: ["language","geography"], level: 1},
{question: "What is the powerhouse of the cell?", answers: ["Nucleus","Mitochondria","Ribosome","Golgi apparatus"], correct: 1, subject: ["science","biology"], level: 2},
{question: "Which instrument has keys, pedals, and strings?", answers: ["Guitar","Violin","Piano","Flute"], correct: 2, subject: ["music"], level: 2},
{question: "Who wrote 'The Odyssey'?", answers: ["Homer","Virgil","Sophocles","Euripides"], correct: 0, subject: ["literature","classics"], level: 6},
{question: "Which country is home to the kangaroo?", answers: ["New Zealand","Australia","India","South Africa"], correct: 1, subject: ["geography","zoology"], level: 1},
{question: "What currency is used in the UK?", answers: ["Euro","Pound Sterling","Dollar","Franc"], correct: 1, subject: ["economics","geography"], level: 1},
{question: "What is 10 squared?", answers: ["100","1000","10","20"], correct: 0, subject: ["math"], level: 0},
{question: "Which mountain is the tallest in the world?", answers: ["K2","Kilimanjaro","Mount Everest","Denali"], correct: 2, subject: ["geography","nature"], level: 2},
{question: "What is the chemical formula for table salt?", answers: ["NaCl","KCl","CaCl₂","MgCl₂"], correct: 0, subject: ["science","chemistry"], level: 2},
{question: "Which planet is closest to the Sun?", answers: ["Venus","Earth","Mercury","Mars"], correct: 2, subject: ["science","astronomy"], level: 1},
{question: "Who wrote 'To Kill a Mockingbird'?", answers: ["Harper Lee","Mark Twain","F. Scott Fitzgerald","Ernest Hemingway"], correct: 0, subject: ["literature"], level: 3},
{question: "What is the capital of Italy?", answers: ["Milan","Venice","Rome","Florence"], correct: 2, subject: ["geography"], level: 1},
{question: "Who is known as the 'Father of Geometry'?", answers: ["Euclid","Pythagoras","Archimedes","Thales"], correct: 0, subject: ["math","history"], level: 5},
{question: "What is the smallest continent by land area?", answers: ["Europe","Australia","Antarctica","South America"], correct: 1, subject: ["geography"], level: 2},
{question: "Which scientist proposed the three laws of motion?", answers: ["Albert Einstein","Nikola Tesla","Galileo Galilei","Isaac Newton"], correct: 3, subject: ["science","physics"], level: 3},
{question: "Which element is represented by 'Au' on the periodic table?", answers: ["Silver","Gold","Copper","Argentum"], correct: 1, subject: ["science","chemistry"], level: 2},
{question: "What is the longest river in the world?", answers: ["Amazon","Nile","Yangtze","Mississippi"], correct: 1, subject: ["geography","nature"], level: 6},
{question: "Who wrote 'The Republic'?", answers: ["Aristotle","Plato","Socrates","Cicero"], correct: 1, subject: ["literature","philosophy"], level: 8},
{question: "What is the capital of Spain?", answers: ["Madrid","Barcelona","Valencia","Seville"], correct: 0, subject: ["geography"], level: 1},
{question: "What phenomenon causes the sky to appear blue?", answers: ["Reflection","Refraction","Rayleigh scattering","Diffraction"], correct: 2, subject: ["science","physics"], level: 4},
{question: "Which war was fought between the North and South regions in the United States?", answers: ["World War I","Revolutionary War","Civil War","War of 1812"], correct: 2, subject: ["history","US"], level: 2},
{question: "What is the chemical symbol for Helium?", answers: ["He","H","Hg","Hi"], correct: 0, subject: ["science","chemistry"], level: 1},
{question: "Who discovered electricity by flying a kite?", answers: ["Nikola Tesla","Benjamin Franklin","Thomas Edison","Alexander Graham Bell"], correct: 1, subject: ["science","history"], level: 3},
{question: "What is the capital of Russia?", answers: ["St. Petersburg","Moscow","Novosibirsk","Kazan"], correct: 1, subject: ["geography"], level: 1},
{question: "Which artist is famous for the painting 'The Persistence of Memory'?", answers: ["Salvador Dalí","Pablo Picasso","Frida Kahlo","Jackson Pollock"], correct: 0, subject: ["art"], level: 5},
{question: "What is the freezing point of water on the Celsius scale?", answers: ["0°C","32°C","100°C","212°C"], correct: 0, subject: ["science","physics"], level: 0},
{question: "Which planet is known as the Red Planet?", answers: ["Venus","Mars","Jupiter","Saturn"], correct: 1, subject: ["science","astronomy"], level: 1},
{question: "Who is the author of 'War and Peace'?", answers: ["Leo Tolstoy","Fyodor Dostoevsky","Anton Chekhov","Ivan Turgenev"], correct: 0, subject: ["literature"], level: 6},
{question: "What is the hardest rock type to scratch?", answers: ["Granite","Obsidian","Diamond","Quartz"], correct: 2, subject: ["science","geology"], level: 3},
{question: "Which country is famous for tulips and windmills?", answers: ["Belgium","Netherlands","Denmark","Switzerland"], correct: 1, subject: ["geography","culture"], level: 2},
{question: "What is the square root of 144?", answers: ["10","11","12","13"], correct: 2, subject: ["math"], level: 1},
{question: "What is the term for the theoretical fabric of spacetime that might allow time loops?", answers: ["Closed timelike curve","Einstein‑Rosen bridge","Temporal mechanics","Wormholes"], correct: 0, subject: ["science","physics","astronomy"], level: 90},
{question: "What is the name of the satellite mapping our Galaxy’s structure?", answers: ["Kepler","Cassini","Gaia","Voyager 1"], correct: 2, subject: ["science","astronomy"], level: 60},
{question: "Which famous paradox asks why we haven't encountered alien civilizations?", answers: ["Zeno’s paradox","Olbers’ paradox","Fermi paradox","Twin paradox"], correct: 2, subject: ["science","astronomy","philosophy"], level: 70},
{question: "What mysterious force drives the accelerated expansion of the universe?", answers: ["Dark matter","Dark energy","Cosmic inflation","Neutrinos"], correct: 1, subject: ["science","cosmology"], level: 50},
{question: "Which telescope observed Earendel, the farthest individual star seen?", answers: ["Spitzer","Hubble Space Telescope","Kepler","James Webb"], correct: 1, subject: ["science","astronomy"], level: 55},
{question: "What astronomical phenomenon causes the sky to appear blue on Earth?", answers: ["Reflection","Refraction","Rayleigh scattering","Diffraction"], correct: 2, subject: ["science","physics"], level: 40},
{question: "What is the current axial tilt of the Earth to the nearest half‑degree?", answers: ["22°","23.5°","24°","25°"], correct: 1, subject: ["science","geography"], level: 50},
{question: "What is the brightest star in the night sky known as?", answers: ["Alpha Centauri","Sirius","Betelgeuse","Polaris"], correct: 1, subject: ["science","astronomy"], level: 30},
{question: "What is the name of the black hole at our Galaxy's center?", answers: ["Cygnus X‑1","Sagittarius A*","Taurus X‑1","Vega Black"], correct: 1, subject: ["science","astronomy"], level: 45},
{question: "What does LIGO study and first detected in 2015?", answers: ["Neutrinos","Cosmic rays","Gravitational waves","Gamma-ray bursts"], correct: 2, subject: ["science","physics"], level: 60},
{question: "What is the name of the first known exoplanet discovered around a Sun‑like star?", answers: ["Proxima b","Kepler‑22b","51 Pegasi b","Trappist‑1e"], correct: 2, subject: ["science","astronomy"], level: 55},
{question: "What process starts star formation in molecular clouds?", answers: ["Ionization","Gravitational collapse","Sagittarius effect","Cosmic inflation"], correct: 1, subject: ["science","astronomy"], level: 50},
{question: "What is the unit astronomers use to express stellar brightness?", answers: ["Flux","Parsec","Magnitude","Luminosity"], correct: 2, subject: ["science","astronomy"], level: 45},
{question: "Which planet rotates in a retrograde direction and has a longer day than its year?", answers: ["Mercury","Venus","Uranus","Mars"], correct: 1, subject: ["science","astronomy"], level: 40},
{question: "What name describes the minimum length scale below which distance loses its usual meaning?", answers: ["Plank scale","Planck length","Planck wavelength","Quantum length"], correct: 1, subject: ["science","physics"], level: 80},
{question: "Which dwarf planet, discovered in 2005, is similar in size to Pluto?", answers: ["Eris","Makemake","Haumea","Ceres"], correct: 0, subject: ["science","astronomy"], level: 50},
{question: "What term describes the event when the moon completely blocks the sun?", answers: ["Transit","Occultation","Eclipse","Aphelion"], correct: 2, subject: ["science","astronomy"], level: 25},
{question: "Which planet’s moon Titan is unique for having a dense atmosphere?", answers: ["Jupiter","Saturn","Uranus","Neptune"], correct: 1, subject: ["science","astronomy","zoology"], level: 35},
{question: "What is the phenomenon in which three celestial bodies align?", answers: ["Syzygy","Eccentricity","Precession","Obliquity"], correct: 0, subject: ["science","astronomy"], level: 60},
{question: "What is the name of the famous star‑forming pillars in the Eagle Nebula?", answers: ["Horsehead pillars","Rosette pillars","Pillars of Creation","Tarantula pillars"], correct: 2, subject: ["science","astronomy"], level: 70},
{question: "Which detection inaugurated multi‑messenger astronomy?", answers: ["GW150914","GW151226","GW170814","GW170817"], correct: 3, subject: ["science","astronomy"], level: 65, hint: "It came from merging neutron stars in 2017"},
{question: "What is the powerhouse of the cell?", answers: ["Nucleus","Mitochondria","Ribosome","Golgi apparatus"], correct: 1, subject: ["science","biology"], level: 10, hint: "It's where most cellular energy is produced"},
{question: "In computer science, what does 'HTTP' stand for?", answers: ["HyperText Transfer Protocol","Hyperlink Text Transmission Protocol","HighText Transfer Protocol","HyperText Transmission Protocol"], correct: 0, subject: ["technology","computing"], level: 20, hint: "It's the foundation of data communication on the web"},
{question: "Which painter cut off his own ear?", answers: ["Claude Monet","Vincent van Gogh","Pablo Picasso","Salvador Dalí"], correct: 1, subject: ["art","history"], level: 15, hint: "He also painted 'Starry Night'"},
{question: "What is 'pi' approximately equal to?", answers: ["3.14","2.72","1.62","4.13"], correct: 0, subject: ["math"], level: 0, hint: "It's the ratio of a circle's circumference to its diameter"},
{question: "Who is the author of '1984'?", answers: ["Aldous Huxley","George Orwell","Ray Bradbury","J.R.R. Tolkien"], correct: 1, subject: ["literature"], level: 20, hint: "He also wrote 'Animal Farm'"},
{question: "What chemical element has the symbol 'Au'?", answers: ["Silver","Gold","Argentum","Aurum"], correct: 1, subject: ["science","chemistry"], level: 10, hint: "It’s a precious metal used in jewelry and currency"},
{question: "Which language is the third most spoken worldwide by native speakers?", answers: ["English","Spanish","Hindi","French"], correct: 2, subject: ["language","geography"], level: 30, hint: "It’s the most spoken language in India"},
{question: "Which river flows through Paris?", answers: ["Thames","Seine","Danube","Rhine"], correct: 1, subject: ["geography"], level: 5, hint: "It shares its name with a famous bridge of books hoping to fall in love"],
{question: "What year did the Berlin Wall fall?", answers: ["1987","1989","1991","1985"], correct: 1, subject: ["history","Europe"], level: 10, hint: "It marked the end of Cold War division in Germany"},
{question: "Which gas do plants absorb during photosynthesis?", answers: ["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"], correct: 1, subject: ["science","biology"], level: 5, hint: "It’s a major greenhouse gas"},
{question: "What is the capital of Australia?", answers: ["Sydney","Melbourne","Canberra","Perth"], correct: 2, subject: ["geography"], level: 10, hint: "It's not the largest Australian city"},
{question: "What metal is liquid at room temperature?", answers: ["Mercury","Lead","Copper","Silver"], correct: 0, subject: ["science","chemistry"], level: 20, hint: "It’s used in thermometers"},
{question: "What is the name of the longest river in the world?", answers: ["Amazon","Nile","Mississippi","Yangtze"], correct: 1, subject: ["geography","nature"], level: 15, hint: "It flows through Egypt and Sudan"},
{question: "Who composed the Four Seasons?", answers: ["Mozart","Beethoven","Vivaldi","Bach"], correct: 2, subject: ["music","classical"], level: 25, hint: "He was a Venetian Baroque composer"},
{question: "What is the smallest prime number?", answers: ["0","1","2","3"], correct: 2, subject: ["math"], level: 0, hint: "It is the only even prime"},
{question: "Which company created the iPhone?", answers: ["Google","Apple","Samsung","Microsoft"], correct: 1, subject: ["technology"], level: 5, hint: "Its logo is an apple with a bite"},
{question: "What is H2O commonly known as?", answers: ["Salt","Hydrogen Peroxide","Water","Sulfuric Acid"], correct: 2, subject: ["science","chemistry"], level: 0, hint: "It’s essential for life"},
{question: "Which planet is known as the Red Planet?", answers: ["Venus","Mars","Jupiter","Saturn"], correct: 1, subject: ["science","astronomy"], level: 5, hint: "Its color comes from iron oxide on its surface"},
{question: "Who painted the 'Mona Lisa'?", answers: ["Michelangelo","Leonardo da Vinci","Raphael","Donatello"], correct: 1, subject: ["art","history"], level: 10, hint: "He was also a pioneering inventor"}
];
